### ISSUE TITLE
`updateVisionSource` replacement?

### ISSUE THREAD

**Issue by phenomen** [Saibot393/perceptive#114]
It seems like `token.updateVisionSource()` was removed and I can't find a way to force update token vision after adding/removing perceptive's vision channel. It's used in "Toggle VC receiver filter of selected Token" macro which is broken right now.

**Comment by Saibot393** [comment]
The bug should now be fixed with v4.2.2.

**Comment by phenomen** [comment]
I mean, it doesn't really fix the issue, since `updateVisionSource()` does not exist anymore and vision is not updated unless I move the token or reselect it.

**Comment by Saibot393** [comment]
Ah, right, sorry, could have sworn that there was reason for why it was no longer necessary in v12. I will look into adding a nother way to update the vision

**Comment by Saibot393** [comment]
Should now be fixed with v4.2.3
