### ISSUE TITLE
[Enhancement] Stealth rules

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/perceptive#19]
This is my bad, because I realize that stealth in Pf2e has degrees of success built into the Perception check (Seek action) to find a Hidden or Undetected creature:

Failure on Seek action: Creature remains in whatever state it was prior to your check (Hidden or Undetected)
Success on Seek action: If creature was Hidden, it becomes Observed (loses Hidden condition). If creature was Undetected, its status changes to Hidden.
Critical Success on Seek action (you beat creature's Stealth DC by 10 or more): Creature becomes Observed unless it was Invisible, in which case it is only Hidden.

I don't know if it's feasible to incorporate these rules into the spotting functionality for creatures, but it would be absolutely amazing if you could! :)

Sorry again for not mentioning this stuff right away. It's been a while since I've looked carefully at the stealth rules for Pf2e.

**Comment by Saibot393** [comment]
I already considered doing that. The problem is the "by the creature"/"by you" part of the rules. I can only apply/change/delete effects for everyone and only selectively turn off the invisible part. 
So for example if someone rolls a critical failure on a sneak action i could only make them be observed by everyone in stead of the token they failed against.

**Comment by Saibot393** [comment]
I have run into a bit of problem rules wise. When a sneaking token has been spotted by only by a normal success/ has failed its stealth check but only with a normal failure it will now be hidden (i have implemented that already). 
Now the problem: The token is now hidden but still has the same result/value used previously for sneaking. If it now checks against the same perception dc it would instantly become observed, therefore rendering the difference between a normal failure and a critical failure mute. 
I am not quite sure how to handle such a case correctly.

**Comment by weepingminotaur** [comment]
Hmm. Since these actions are all combat actions, perhaps this should just be handled by a macro bundled with the module that Seeks in either a 30-foot cone or 15-foot burst centred on the seeking token (and one would turn off the option to spot it passively for that Undetected token). That way, it's only one check (using the macro). If the player wants to spend another action to Seek, then they have to roll again and beat the creature's Perception DC again. Does this make sense?

**Comment by Saibot393** [comment]
Yes, if i only limit the stealth removal to active checks that shouldn't be a problem.

**Comment by weepingminotaur** [comment]
Yeah, I think limiting stealth removal to PC or NPC tokens would be fine. You'd still want passive to be able to toggle visibility for loot actors and ping players for walls, of course. 

This is such a cool module! I can't wait to wow my players with it next session. :)

**Comment by Saibot393** [comment]
Even things like reducing undetected to hidden will be possible. Btw., my ETA for the v2.0.0 is around friday. I have the ground work pretty much done and most features are basically implemented (i updated the changelog to include evrything i am done with). Pretty much the only thing missing, besides the localizations, are the hidden removel and and the conditional range checks (and abit of bug testing to be certain).

**Comment by Saibot393** [comment]
The rules have been implemented with v2.0.0, i will eave this issue open for now in case i forgot something

**Comment by weepingminotaur** [comment]
Just testing the macros with the new "in combat" setting, encountering some unexpected behaviour:

- The macros seem to be bound by the Spotting Range value, not the 15-foot burst or 30-foot cone. For example, with an Undetected token, the seeking token will find nothing on a successful check within a 15-foot burst if the Spotting Range value is set to 10. Only when the seeker is within 10 feet will the check work and ping/reveal the token. Maybe add a "always out of combat" option to the Apply Ranges drop-down? You'd want it always on in exploration but obviously not in an encounter.
- The cone macro rolls the check but doesn't seem to work. Do I have to have a value defined in Spotting Cone Range?

**Comment by Saibot393** [comment]
- I just tested the 15 foot burst check and it seems to work fine for me. Do you have "Use border to border range" activated? What "constealltion" were the tokens in you tested the range with, could send me a screenshot? I will add an always out of combat setting to range appication in the next release, should be raltively easy to do.
- There indeed seems to be something bugged with the cone macro, i will look into it

**Comment by weepingminotaur** [comment]
Ah, I didn't have border to border range on. I will test again with that option on and off and report back if the behaviour persists.
The cone macro should allow the user to rotate and place the template, I guess, since it can point in different directions?

**Comment by Saibot393** [comment]
The cone for the cone range will rotate with the token the macro is used with.

**Comment by weepingminotaur** [comment]
Wait, shouldn't the option be "out of combat for both", not in combat? In combat, for PF2e, players are using the macros, so they don't need auto-reveal on the Spotting Range.

**Comment by weepingminotaur** [comment]
Tested the update and spotting within 15-foot burst works if "border to border" is on, but not if it's off. In the attached screenshot, the seeking token is within 15 feet of the undead but the Seek check in chat hasn't "found" the undead.

The 30-foot cone macro still doesn't work, though. No console errors either.

<img width="1227" alt="Screenshot 2023-09-28 at 1 05 00 PM" src="https://github.com/Saibot393/perceptive/assets/90105219/815d5457-4e5e-4b31-9db4-92f0f1ca12c7">

**Comment by Saibot393** [comment]
Right, it is expected, that in the above image the 15 foot burst doesn't find the token if border to border is off, since the center to center distance is ~15.8 foot ((5^2 + 15^2)^0.5).

Regarding the 30 foot cone macro: Are you using the new updated macro/have you updated your macro since v2.0.4?

**Comment by weepingminotaur** [comment]
I reimported the macro after updating 2.0.4 and it still doesn't work.

**Comment by Saibot393** [comment]
Thats strange, could you send me screenshot of your range settings and the macros code?

**Comment by weepingminotaur** [comment]
> Thats strange, could you send me screenshot of your range settings and the macros code?

Wait, do I have to specify a cone range in module settings? If so, then I'll re-test, since I currently have it at 0.

**Comment by Saibot393** [comment]
Normally not, but i want to test it with your settings, there might be a setting specific bug

**Comment by Saibot393** [comment]
And a screenshot of the situation in which you tested the cone macro would also be helpful

**Comment by weepingminotaur** [comment]
> And a screenshot of the situation in which you tested the cone macro would also be helpful

It was just a combat situation with a PC token and an Undetected enemy token. Selecting the PC token and clicking the 30-foot cone macro did nothing.

**Comment by Saibot393** [comment]
Were they standing on a diagonal to one another, similar to this screenshot?
![image](https://github.com/Saibot393/perceptive/assets/137942782/43e64dd1-dbb4-418e-b955-0160268f5490)

**Comment by Saibot393** [comment]
If so, it should be fixed with v2.0.5

**Comment by weepingminotaur** [comment]
Not as wide a diagonal, but yeah.

**Comment by weepingminotaur** [comment]
Cone macro still not working. The template isn't being put down. Screenshot attached. The PC (Skarr) should have made the undead north of him visible with that Seek check.
<img width="1139" alt="Screenshot 2023-09-28 at 4 51 55 PM" src="https://github.com/Saibot393/perceptive/assets/90105219/4576f449-955a-475c-aaab-03e9abb9dadf">

**Comment by Saibot393** [comment]
The NPC seems to be facing south, therefore the macro would apply the cone in a southward direction

**Comment by Saibot393** [comment]
I could add an option though, to rotate the direction in which the cone is applied by 180°

**Comment by weepingminotaur** [comment]
I appreciate that, but would you also be able to add an option to disable auto-direction on the cone and just let the player lay down a template? I don't actually have token rotation on, and I suspect that others would be in the same position.

**Comment by Saibot393** [comment]
I will see what i can do, but i can't guarantee for anything. Templates isn't a system i've had a deeper lock at yet.

**Comment by weepingminotaur** [comment]
OK, thanks for looking into it. And good to know about facing -- since facing has no mechanical impact in Pf2e, I hadn't thought to rotate the token before doing the Seek cone check. It works now, though!

**Comment by Saibot393** [comment]
I have just released v2.0.7 which add an additional macor to use seek with a 30 feet burst with a template. When this macro is used, a template will show up, that can be rotated, to aplly the template with the check, the player can click its icon. I am not 100% happy with the implementation but it is the best i could come up for now.

**Comment by Saibot393** [comment]
I think everything discussed in this issue should be implemented now, or did i miss something? If not i would close this issue.

**Comment by weepingminotaur** [comment]
Just one issue: last session, one of my players said he could see a hidden loot actor even though his token wasn't in range to spot it passively (out of combat). Any idea how or why?

**Comment by weepingminotaur** [comment]
> Wait, shouldn't the option be "out of combat for both", not in combat? In combat, for PF2e, players are using the macros, so they don't need auto-reveal on the Spotting Range.

Was this ever resolved? For Apply Ranges, the menu option is still "in combat only (both checks)", where it should be "out of combat only (both checks)". In combat, you aren't using the Spotting Range, because you're going macro all the way (Seek in 15-foot burst or 30-foot cone).

**Comment by Saibot393** [comment]
Sorry, i must have missed your comment regarding the "out of combat" setting for ranges, i will add it in a quick patch.
Regarding the problem with your player, were they controlling two or more tokens at the time that happened? Perceptive will use all currently controlled tokens as vision sources (even if they don't have vision themself)

**Comment by Saibot393** [comment]
I have added the out of combat only setting with v2.4.1

**Comment by weepingminotaur** [comment]
> Sorry, i missed your request regarding the "out of combat" setting for ranges, i will add it in a quick patch. Regarding the problem with your player, were they controlling two or more tokens at the time that happened? Perceptive will use all currently controlled tokens as vision sources (even if they don't have vision themself)

They didn't have two tokens controlled as far as I know. I will see if it comes up again next session and whether there are any console errors.

**Comment by Saibot393** [comment]
> Just one issue: last session, one of my players said he could see a hidden loot actor even though his token wasn't in range to spot it passively (out of combat). Any idea how or why?

There is a chance that this bug was fixed with v2.6.4

**Comment by Saibot393** [comment]
I think everything discussed in this issue should now be implemented/fixed. Unless i hear otherwise i will closing it soon.
