### ISSUE TITLE
[PF2e] Controls don't work, but module is active

### ISSUE THREAD

**Issue by Mjb141** [Saibot393/perceptive#27]
Active modules list:

```
Actually Private Messages (ex Actually Private Rolls)
Advanced Macros
Automated Animations
Battlezoo Ancestries: Dragons for Pathfinder 2e by Roll for Combat
Battlezoo Bestiary for Pathfinder 2e by Roll For Combat
Dice So Nice!
Force Client Settings
Health Estimate
JB2A - Patreon Complete Collection
libWrapper
Monk's Active Tile Triggers
Monk's Wall Enhancement
PF2e Companion Compendia
Gatewalkers - Basis Pack
Gatewalkers - The Seventh Arch
Gatewalkers - They Watched the Stars
Gatewalkers - Dreamers of the Nameless Spires
Pathfinder Beginner Box
PF2e Dailies
pf2E Extempore Effects
PF2e Investigators: Pivots & Complications
PF2e Animation Macros
Pf2E Modifiers Matter
PF2e Staves
PF2e Target Damage
Pathfinder Token Pack: Bestiaries
PopOut!Roll Tracker
Sequencersocketlib
TheRipper93's Module Hub
Tile Scroll
Token Attacher
Token Z
Tokenizer
Wall Height
Warp Gate
Witches+
PF2e Workbench
``` 

None of the controls do anything, nor does changing them to other (unbound) keys. Console shows stacks of `True` or `False` counting up from `PerceptiveMouseHandler.js` but nothing is actually happening, even when `True`.

**Comment by Saibot393** [comment]
I just tested it with these modules enabled (at least most of them, some seem to be premium modules) and it seems to work for me. 
Could you send me screenshots of your perceptive world settings, the perceptive settings of the door you tried it with and a screenshot of your scene around the door containing the token you tried it with?

**Comment by Mjb141** [comment]
I've uninstalled, installed, reset controls, and at least `Peek Lock` is working from a keyboard shortcut and mouse click. Scrolling for any kind of small angle opening still isn't working. I'll keep testing stuff and if I get more detail I'll post it

**Comment by Saibot393** [comment]
Good to hear that at least lock peeking works now.

**Comment by Ironxxx** [comment]
I'm having the same issue, these are the modules I have running (below). It does display a yellow warning about Arms Reach and Monk's Wall Enhancement but I've disabled both and it still doesn't work. I've tried changing the controls. I don't get any other errors.

### Active Modules
Advanced Drawing Tools v2.1.0 [Bugs URL](https://github.com/dev7355608/advanced-drawing-tools/issues)
Alternative Token Visibility v0.5.8
Arbron’s Improved HP Bar v2.2.4 [Bugs URL](https://github.com/arbron/fvtt-hp-bar/issues)
Arms Reach vv2.3.3 [Bugs URL](https://github.com/p4535992/foundryvtt-arms-reach/issues)
Chat Images v3.2
DFreds Droppables v3.0.1 [Bugs URL](https://github.com/DFreds/dfreds-droppables/issues)
Dice So Nice! v4.6.8 [Bugs URL](https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues)
Entice with Dice so Nice v0.1.0
Lordu's Custom Dice for Dice So Nice v0.39
Orksork's Emoji Dice So Nice Nice Dice v1.1
Dice Stats v1.14.3
Dice Tray v1.5.3
Drag Ruler v1.13.8 [Bugs URL](https://github.com/manuelVo/foundryvtt-drag-ruler/issues)
PF2e Drag Ruler Integration v3.0.3
Enhanced Terrain Layer v10.09 [Bugs URL](https://github.com/ironmonk88/enhanced-terrain-layer/issues)
Terrain Ruler v1.7.6 [Bugs URL](https://github.com/manuelVo/foundryvtt-terrain-ruler/issues)
Follow Me! v10.0.2
Forien's Quest Log v0.7.12 [Bugs URL](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/issues)
FXMaster v4.0.2 [Bugs URL](https://github.com/ghost-fvtt/fxmaster/issues)
Hide GM Rolls v0.15.3 [Bugs URL](https://github.com/sPOiDar/fvtt-module-hide-gm-rolls/issues)
Image Hover v3.0.3 [Bugs URL](https://github.com/Eriku33/Foundry-VTT-Image-Hover/issues)
Item Piles v2.7.15 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues)
JB2A - Patreon Complete Collection v0.6.1
CodeMirror v5.58.3-fvtt5
lib - Color Settings v2.9.1
libWrapper v1.12.13.0 [Bugs URL](https://github.com/ruipin/fvtt-lib-wrapper/issues)
Settings Extender v1.2.2
socketlib v1.0.13 [Bugs URL](https://github.com/manuelVo/foundryvtt-socketlib/issues)
Token Action HUD Core v1.4.20
Abomination Vaults maps remake v2.3.2
Module Management+ v2.2.3 [Bugs URL](https://github.com/mouse0270/module-credits/issues)
Monk's Active Tile Triggers v11.11 [Bugs URL](https://github.com/ironmonk88/monks-active-tiles/issues)
Monk's Bloodsplats v11.05 [Bugs URL](https://github.com/ironmonk88/monks-bloodsplats/issues)
Monk's Combat Details v11.08 [Bugs URL](https://github.com/ironmonk88/monks-combat-details/issues)
Monk's Combat Marker v11.02 [Bugs URL](https://github.com/ironmonk88/monks-combat-marker/issues)
Monk's Hotbar Expansion v10.1 [Bugs URL](https://github.com/ironmonk88/hotbar-expansion/issues)
Monk's Little Details v11.05 [Bugs URL](https://github.com/ironmonk88/monks-little-details/issues)
Monk's Sound Enhancements v11.04 [Bugs URL](https://github.com/ironmonk88/monks-sound-enhancements/issues)
Monk's Wall Enhancement v11.02 [Bugs URL](https://github.com/ironmonk88/monks-wall-enhancement/issues)
Ownership Viewer v11.4 [Bugs URL](https://github.com/mclemente/fvtt-module-permission-viewer/issues)
Perceptive v2.1.3
PF2e Action Support v0.2.57 [Bugs URL](https://github.com/reyzor1991/foundry-vtt-pf2e-action-support/issues)
PF2e Companion Compendia v6.0
PF2e Dailies v2.12.3 [Bugs URL](https://github.com/reonZ/pf2e-dailies/issues)
PF2e Expansion Pack v2.3
PF2e Exploration Activities v1.2.1
PF2E Exploration Effects v3.0.0
pf2E Extempore Effects v1.7.4 [Bugs URL](https://github.com/shemetz/pf2e-extempore-effects/issues)
PF2E Fatigue v1.3.5
PF2e Flat Check v1.7.0 [Bugs URL](https://github.com/jessev14/pf2-flat-check/issues)
PF2e Flip Token v0.0.3 [Bugs URL](https://github.com/reyzor1991/foundry-vtt-pf2e-flip-token/issues)
PF2e Giveth v1.4.0 [Bugs URL](https://github.com/reonZ/pf2e-giveth/issues)
PF2e GM Screen v1.1.3
PF2e Hands Management (Reminder) v0.0.13 [Bugs URL](https://github.com/reyzor1991/foundry-vtt-pf2e-notification/issues)
PF2e Keybind Menagerie v5.3.2
Pf2E Modifiers Matter v1.8.2 [Bugs URL](https://github.com/shemetz/pf2e-modifiers-matter/issues)
PF2e Psychic Amps v2.0
PF2e Ranged Combat v4.0.4 [Bugs URL](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/issues)
PF2e Rule Element Generator v3.0.2 [Bugs URL](https://gitlab.com/pearcebasmanm/rule-element-generator/-/issues)
PF2e Stances v1.6.1 [Bugs URL](https://github.com/reonZ/pf2e-stances/issues)
PF2e Staves v1.3.1
PF2e Target Damage v2.4.15 [Bugs URL](https://github.com/MrVauxs/PF2e-Target-Damage/issues)
PF2e Workbench v5.20.1 [Bugs URL](https://github.com/xdy/xdy-pf2e-workbench/issues)
Pin Cushion v1.9.10 [Bugs URL](https://github.com/p4535992/foundryvtt-pin-cushion/issues)
Polyglot v2.3.4
Quick Insert - Search Widget v2.8.3 [Bugs URL](https://gitlab.com/fvtt-modules-lab/quick-insert/-/issues)
Scene Transitions v0.5.0 [Bugs URL](https://github.com/p4535992/foundryvtt-scene-transitions/issues)
Select tool everywhere v1.4.1
Sequencer v3.1.4 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-Sequencer/issues)
Automated Animations v4.2.67
PF2e Animation Macros v2.16.9
Automated Evocations - Companion Manager v2.0.3
Simple Calendar v2.4.3 [Bugs URL](https://github.com/vigoren/foundryvtt-simple-calendar/issues)
Weather Reports v1.0.1
Smart Target v1.0.1 [Bugs URL](https://github.com/theripper93/Smart-Target/issues)
Swarms v10.0.3
Token Action HUD Pathfinder 2e v1.4.15
Token Attacher vv4.5.13
Token Elevator v1.4.4 [Bugs URL](https://gitlab.com/Weissrolf/token-elevator/-/issues)
Token Health v0.6.0
Tokenizer v4.2.5
Token Magic FX v0.6.4.1
PF2e TokenMagic Integration v0.2.0
Token Magic FX - Automatic Wounds v1.1.3 [Bugs URL](https://github.com/shemetz/tokenmagic-automatic-wounds/issues)
Token Tooltip Alt v3.2.1
PF2e Dorako UI v2.8.5 [Bugs URL](https://github.com/Dorako/pf2e-dorako-ui/issues)
Warp Gate v1.18.3
Z Scatter v1.2.8

**Comment by Saibot393** [comment]
Thank you, maybe i can pin it down with the additional data.

**Comment by Saibot393** [comment]
Could one of you send me a screenshot of the perceptive settings of one of the doors you tried to lock peek/move?

**Comment by Ironxxx** [comment]
![door settings perceptive](https://github.com/Saibot393/perceptive/assets/65545400/cab2883e-7d05-4952-8018-6d314be6dea6)

There you go

**Comment by Saibot393** [comment]
Thank you. I have done a few tests with the modules you both have active ut i cant seem to replacte the behaviour. I have released a new version v2.2.0 which will probably not fix the issue but adds a client setting "Message popups" which could help narrow down the source of the problem. Could you tell me what happens when you either peek a door or move a door while this setting is activated?

**Comment by Ironxxx** [comment]
Nothing happens, still the same. 
If I lock the door and try and use O or Ctrl Right Click it plays the locked noise, so the controls are being recognised. 
If I change it to a swinging door, the mouse wheel will work one way but not the other (will swing toward the player).

**Comment by Saibot393** [comment]
What happens if the door is set to sliding? Does it also only slide one way?

**Comment by Ironxxx** [comment]
Sliding and swinging works. The noise the door makes is played about 4 - 6 times when first slid or swung open. The controls to peek do not work but I can use swinging doors as a workaround

**Comment by Saibot393** [comment]
Does the "Mouse Move door fast" key work? (you may have to rebind it)

**Comment by Ironxxx** [comment]
It works if it is rebound, I moved it to Right Shift

**Comment by Saibot393** [comment]
I did some further testing but still cant replicate the issue. If you want you could send me your world file (without any images, sounds...) and i could take a direct look at it. There is a chance, that some specific setting is at fault here.

**Comment by Saibot393** [comment]
I have noticed that you have a few modules enabled that don't officially work with Foundry v11 (Enhanced Terrain Layer, Arbron’s Improved HP Bar, Follow Me!), have you forced them manually to work with Foundry v11, i.e. changed their module.json file?

**Comment by Ironxxx** [comment]
No, I've only just noticed that E.Terrain Layer hasn't been updated, it hasn't caused any issues yet. 
The others are still working, no issues that I've noticed.

**Comment by Saibot393** [comment]
I could not replicate this problem until this day, is this still happening?

**Comment by Ironxxx** [comment]
Hi, thanks for continuing to look at this. I turned the mod back on to test and all is working from what I can tell. It throws up a conflict with libwrapper and terrainmapper (below) but otherwise works fine.

Libwrapper:
```
libWrapper-notifications.js:90 [W] libWrapper: module Perceptive and [module Arms Reach, module Monk's Wall Enhancement] modify the same FoundryVTT functionality and are more likely to conflict.
Module perceptive did not chain the wrapper for 'DoorControl.prototype._onRightDown'.
🎁console_ui @ libWrapper-notifications.js:90
🎁conflict @ libWrapper-notifications.js:116
🎁_cleanup_call_wrapper @ libWrapper-wrapper.js:740
(anonymous) @ libWrapper-wrapper.js:651
Promise.then
🎁call_wrapper @ libWrapper-wrapper.js:649
🎁DoorControl.prototype._onRightDown#0 @ libWrapper-wrapper.js:193
notifyListeners @ EventBoundary.ts:1454
notifyTarget @ EventBoundary.ts:662
propagate @ EventBoundary.ts:299
dispatchEvent @ EventBoundary.ts:210
mapPointerDown @ EventBoundary.ts:693
mapEvent @ EventBoundary.ts:231
onPointerDown @ EventSystem.ts:373
```


Terrainmapper:
```
foundry.js:635 Foundry VTT | Error thrown in hooked function 'preUpdateWallHook' for hook 'preUpdateWall'
#call @ foundry.js:635Understand this warning
foundry.js:655 Error: Error thrown in hooked function 'preUpdateWallHook' for hook 'preUpdateWall'. Maximum depth exceeded
[Detected 2 packages: terrainmapper(0.4.9), perceptive(4.2.16)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.call (foundry.js:614:38)
    at #preUpdateDocumentArray (foundry-esm.js:56512:46)
    at async ClientDatabaseBackendPF2e._updateDocuments (foundry-esm.js:56469:7)
    at async WallDocument.updateDocuments (foundry-esm.js:11473:23)
    at async WallDocument.update (foundry-esm.js:11584:23)
    at async WallUtils.syncWallfromDoor (WallUtils.js:128:4)
    at async PeekingManager.updateDoorPeekingWall (PeekingScript.js:264:8)
    at async vAction (PeekingScript.js:61:6)Caused by: Error: Maximum depth exceeded
[Detected 2 packages: terrainmapper(0.4.9), perceptive(4.2.16)]
    at flattenObject (foundry-esm.js:3013:13)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at flattenObject (foundry-esm.js:3019:21)
    at Object.flattenObject (foundry-esm.js:3019:21)
    at Object.preUpdateWallHook [as fn] (elevation.js:253:34)
    at #call (foundry.js:632:20)
    at Hooks.call (foundry.js:614:38)
    at #preUpdateDocumentArray (foundry-esm.js:56512:46)
    at async ClientDatabaseBackendPF2e._updateDocuments (foundry-esm.js:56469:7)
    at async WallDocument.updateDocuments (foundry-esm.js:11473:23)
    at async WallDocument.update (foundry-esm.js:11584:23)
    at async WallUtils.syncWallfromDoor (WallUtils.js:128:4)
    at async PeekingManager.updateDoorPeekingWall (PeekingScript.js:264:8)
    at async vAction (PeekingScript.js:61:6)
```

**Comment by Saibot393** [comment]
I will take a look at these warnings, the first one is probably fine, the second one could be concerning, i will do a few tests. Glad to hear, that is working so far
