### ISSUE TITLE
[Bug] Incompatibility with Levels Module

### ISSUE THREAD

**Issue by lukekostrewa** [Saibot393/perceptive#65]
When I have the Perceptive module active in a scene using the Levels module it makes all doors visible on all levels
![20240125105208](https://github.com/Saibot393/perceptive/assets/152325522/d8224eb2-351b-429a-8992-d6801f006e83)
![20240125105221](https://github.com/Saibot393/perceptive/assets/152325522/29b6120b-53a2-4037-bfb0-7a3242e46106)
![20240125105231](https://github.com/Saibot393/perceptive/assets/152325522/56d758b6-8360-4f45-8eaa-13e624297c63)

**Comment by Saibot393** [comment]
I will look into it, might take a few days though.

**Comment by lukekostrewa** [comment]
No worries, there's no rush. Everything else has worked great, fantastic module

**Comment by Saibot393** [comment]
Glad to hear that

**Comment by Saibot393** [comment]
The bug should now be fixed with v3.2.0

**Comment by lukekostrewa** [comment]
I have it updated to v3.2.1 and levels is updated to v4.3.5 but I'm still having the same issue

**Comment by Saibot393** [comment]
I had a look and i can indeed still replicate the behaviour, but only as a GM if i don't have layer selected in the layers tool. I will look inot ifixing it. Are there any other scenarios in which this happens to you?

**Comment by Saibot393** [comment]
I think it should now be fixed for good, i forgot to add the LOS test at one point, i will leave the issue open until i get confirmation
