### ISSUE TITLE
Passive Perception DC issue

### ISSUE THREAD

**Issue by VirusNik21** [Saibot393/perceptive#95]
Please help, for some reason, when setting a certain Passive Perception DC value in a token, after stealth check - this value is reset to -1 on a token.
Settings “Auto stealth behavior” is set to “Set only active perception DC”. 
I don't understand how to implement the predefined Passive Perception DC value.
FVTT V12

For example, for a goblin to go into stealth, the Active Perception DC is equal to the value of the stealth check rolled, and the Passive DC remains equal to the value written in the stat block.
See the image bellow.
Settings.
![Settings](https://github.com/Saibot393/perceptive/assets/150345729/b33f15d3-6249-492b-b9dd-0d99950a99af)
Before Skillcheck
![Before Skillcheck](https://github.com/Saibot393/perceptive/assets/150345729/f823b60e-1e12-4f68-9571-7513836c008a)
After Skillcheck.
![After Skillcheck](https://github.com/Saibot393/perceptive/assets/150345729/7c2a6272-882f-40a7-b0f1-689e1bd28b32)

**Comment by Saibot393** [comment]
There was small bug, should now be fixed with v4.0.2

**Comment by VirusNik21** [comment]
Unfortunately, it still doesn't work.
I set the passive perception DC with my hands in the token settings (value in the "Passive Perception DC" field in the settings has no effect).
After the stealth check occurs, the value is correct. 
But after the token is revealed from the invisibility state, it is reset to -1 again.
Maybe I'm doing something wrong?

Screens below:
1) Settings
![Settings](https://github.com/Saibot393/perceptive/assets/150345729/e5c0748a-b595-4526-b195-270e239583fe)
2) Token settings before stealth roll
![token 1](https://github.com/Saibot393/perceptive/assets/150345729/04782397-11b3-4595-b91c-5c8dccdde028)
3) Token settings after stealth roll
![token 2](https://github.com/Saibot393/perceptive/assets/150345729/fc394f60-2f84-40ac-9e10-b74da4b479fb)
4) Token settings after reveal by skillcheck perception off another token (hero)
 ![token 3](https://github.com/Saibot393/perceptive/assets/150345729/3b3eb84e-68b4-48ef-aa41-32939fd88b12)


And this is a video capture on the screen with this issue
https://drive.google.com/file/d/15rNta93VDAoN5J3OwIWjRKXhMrScuD6G/view?usp=sharing

**Comment by Saibot393** [comment]
Ah, ok. That is technically intended, but i agree that resetting this value is unnecessary, i will change that in a quick update

**Comment by Saibot393** [comment]
The passive DC should no longer reset with v4.0.3

**Comment by VirusNik21** [comment]
It's work as expected, thank you very much. Great work :+1:
